user  nginx;
worker_processes 1;

pid        /etc/nginx/nginx.pid;

events {

  worker_connections 1024;
}


http {

  include mime.types;
  default_type application/octet-stream;

  log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';
  sendfile on;
  include /etc/nginx/conf.d/*.conf;
  client_body_buffer_size  1K;
  client_header_buffer_size 1k;
  client_max_body_size 1M;
  #large_client_header_buffers 2 1k;

  client_body_timeout 10;
  client_header_timeout 10;
  #keepalive_timeout 5 5;
  send_timeout 10;

  error_log  /etc/nginx/logs/server_error.log  info;
  access_log /etc/nginx/logs/server_access.log;

  proxy_cache_path ../pagecache levels=1:2 keys_zone=pagecache:100m max_size=1g inactive=2h use_temp_path=off;
  keepalive_timeout  65;
  gzip  on;

  include /etc/nginx/conf.d/*.conf;
}
