server {
    listen 443 ssl;
    listen [::]:443;
    server_name gotcha;

    ssl_certificate /etc/nginx/certs/gotcha.pem;
    ssl_certificate_key /etc/nginx/certs/gotcha.key;    root /usr/share/nginx/html/frontend;

    access_log /etc/nginx/logs/app_ssl_web.log;
    error_log /etc/nginx/logs/app_ssl_error.log;

    real_ip_header X-Forwarded-For;
    real_ip_recursive on;

    location / {
       root /usr/share/nginx/html/frontend;
       index index.html;
       try_files $uri $uri/ /index.html;
    }

    # proxy - Panda BE
    location /public/ {
        proxy_pass http://172.16.0.42:8080/public/;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
   }

    location /protected/ {
        proxy_pass http://172.16.0.42:8080/protected/;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
   }

    location /admin/ {
        proxy_pass http://172.16.0.42:8080/admin/;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
   }


}

