apiVersion: apps/v1
kind: Deployment
metadata:
  name: gotcha-backend
  namespace: gotcha
spec:
  replicas: 0
  selector:
    matchLabels:
      app: gotcha-backend
  template:
    metadata:
      labels:
        app: gotcha-backend
    spec:
      containers:
      - name: backend
        image: 558050136406.dkr.ecr.eu-west-1.amazonaws.com/thbs-gotcha-backend:latest
        imagePullPolicy: Always
        env:
        - name: LOG_FILENAME
          value: "/apps/logs/gotcha.log"
        - name: APP_NAME
          valueFrom:
            secretKeyRef:
              name: gotcha-backend-secret
              key: APP_NAME

        - name: JWT_EXPIRY_TIME
          valueFrom:
            secretKeyRef:
              name: gotcha-backend-secret
              key: JWT_EXPIRY_TIME

        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: gotcha-backend-secret
              key: JWT_SECRET_KEY

        - name: LOG_FILENAME
          valueFrom:
            secretKeyRef:
              name: gotcha-backend-secret
              key: LOG_FILENAME

        - name: LOG_LEVEL
          valueFrom:
            secretKeyRef:
              name: gotcha-backend-secret
              key: LOG_LEVEL

        - name: MONGODB_URL
          valueFrom:
            secretKeyRef:
              name: gotcha-backend-secret
              key: MONGODB_URL

        - name: PORT
          valueFrom:
            secretKeyRef:
              name: gotcha-backend-secret
              key: PORT  
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: gotcha-backend-svc
  namespace: gotcha
spec:
  selector:
    app: gotcha-backend
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
